#!/bin/bash


rm -rf documentation
mkdir documentation


for i in Custom*.xml; do 
   DOCUFILE="documentation/${i%%.xml}.html"
   DOCUFILE="$(echo $DOCUFILE|tr ' ' '_')"
   xalan -in "$i" -out $DOCUFILE -xsl transform.xsl; 
   echo "<option value=\"$(echo ${i%%.xml}|tr ' ' '_').html\"> ${i%%.xml}</option>" >> documentation/index.html
done


